services:
  libreriaweb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: apache_web
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ../../docs:/var/www/html
    depends_on:
      - libreriadb
    networks:
      - libreria-network
    restart: unless-stopped

  libreriadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: libreriaElLugar2026
      MYSQL_DATABASE: ElLugarDB
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - libreria-network
    
volumes:
  mariadb_data:

networks:
  libreria-network: